### ISSUE TITLE
Parse error: return followed by "-" element

### ISSUE THREAD

**Issue by sebafonte** [lammas/glsl-man#1]
**When parsing**:

precision highp float;
varying float xx, yy;

float test (vec2 p) {
    return -1.0;
}

void main(void) {
    gl_FragColor = vec3(0.0);
}

**I see the following error**: "Expected "(", ".", "0", ";", "false", "true", [0-9], [1-9], identifier, t
ype name or whitespace but "-" found.". 

If i put -1.0 into parenthesis i can parse without problems.

**Comment by lammas** [comment]
Thanks, I will look into it.

**Comment by sebafonte** [comment]
Thanks, by the way excellent module. When it's finished i'll show you what
i'm doing with it if you want hehe.

**Comment by lammas** [comment]
Update to **v1.0.6** for a fix.

In response to your now vanished comment: I would very much like to see what you're doing with it. Feedback is always nice and seeing your stuff used by others is the best reward for making something.

Edit: noticed the same problem for int constants and fixed that too.

**Comment by sebafonte** [comment]
Thank you so much. I'll try to contribute fixing or reporting at least if i
find something. I found this module best glsl parser for nodejs, great job.
Give me some week and i'll show you something about it.
