### ISSUE TITLE
Can't parse unary operators after a return

### ISSUE THREAD

**Issue by DiThi** [lammas/glsl-man#10]
`glsl.parse("float test(){return -pow(1, 2);}")`

It's correct GLSL but it says:

> Expected "!=", "%", "%=", "&", "&&", "&=", "*", "*=", "+", "++", "+=", "-", "--", "-=", ".", "/", "/=", ";", "<", "<<", "<<=", "=", "==", ">", ">>", ">>=", "?", "[", "^", "^=", "^^", "|", "|=", "||", [0-9], [Ee], [\-0-9], or whitespace but "p" found.

**Comment by lammas** [comment]
Thanks :)
I'll look into this as soon as possible, but I cannot promise a solution today.

**Comment by DiThi** [comment]
@lammas No hurries, I worked around that with a regexp for now.

**Comment by lammas** [comment]
Alright, for once it seems it was more trivial to fix than I anticipated. 🍡

**Comment by lammas** [comment]
v1.1.8 with the fix is now up.
