### ISSUE TITLE
Mishandling of parenthesis

### ISSUE THREAD

**Issue by DiThi** [lammas/glsl-man#12]
`glsl.string(glsl.parse("void main(){global = (viewinvmat * vec4(local, 1.0)).xyz;}"))`

That removes the very necessary parenthesis around the expression. After some more toying around, it seems it fails for other cases (such as unary operators) that are not caught by the GLSL compiler because they remain the correct type.

**Comment by lammas** [comment]
Should be fixed now in glsl-man@1.1.9

**Comment by DiThi** [comment]
Thanks, that was quick! I can remove almost all workarounds now.

However this one issue persists:

`glsl.string(glsl.parse("int quick_floor(float x){return int(x) - ((x < 0.0) ? 1 : 0);}"))`

Shouldn't the rules for no parenthesis depend on the priority between operators? (I don't know if that's the issue, I didn't look deep in the code)

Well, when working around this one it seems there are no other issues.

**Comment by lammas** [comment]
Seems I had missed ternary operators. The entire parentheses generating business in the deparser is currently far from ideal, but it should at least generate correct code now for ternary operators as well.
