### ISSUE TITLE
Empty bodies without brackets fail

### ISSUE THREAD

**Issue by DiThi** [lammas/glsl-man#13]
if (misttype == 1.0) ;
    else fac = sqrt(fac);

Looks like this is valid GLSL (as I've used it extensively) but emits the code without the `;` which is a syntax error.

`glsl.string(glsl.parse("void main(){if (misttype == 1.0) ; else fac = sqrt(fac);}"))`

**Comment by lammas** [comment]
Should be fixed now in glsl-man@1.1.9
