### ISSUE TITLE
Can't parse array arguments

### ISSUE THREAD

**Issue by DiThi** [lammas/glsl-man#14]
`glsl.string(glsl.parse("void test(vec3 test1[4], out vec3 test2[4]){}"))`

The `[4]` are removed.

edit: Sorry I have so much unforgiving GLSL code.

**Comment by lammas** [comment]
No problem, this is great. ʕ•ᴥ•ʔ

**Comment by lammas** [comment]
Should be fixed now in glsl-man@1.1.9
