### ISSUE TITLE
Deparse error: missing ";" after for

### ISSUE THREAD

**Issue by sebafonte** [lammas/glsl-man#2]
**When deparsing the AST of:**

varying float xx, yy;
void main() {
    float value = 0.0;
    for (int i=0; i == 10; i++) value = 1.0;
    mainImage(gl_FragColor, vec2(xx, yy));
}

**The result expression has not a ";"** after value = 1.0, resulting in an bad formed glsl expression:

varying float xx, yy;
void main() {
    float value = 0.0;
    for (int i = 0; i == 10; i++) value = 1.0   mainImage(gl_FragColor, vec2(xx, yy));
}

**Comment by lammas** [comment]
Should be fixed in 1.0.7.
