### ISSUE TITLE
Deparse error: else if

### ISSUE THREAD

**Issue by sebafonte** [lammas/glsl-man#3]
**When deparsing the AST of:**

void main() {
    float value = 0.0;
    if (xx == 1.0)
        value = 1.0;
    else if (yy == 2.0)
        value = 3.0;
}

**The result expression has replaced "else if" with "elseif"**, resulting in an bad formed glsl expression:

void main() {
    float value = 0.0;
    if (xx == 1.0) value = 1.0  elseif (yy == 2.0) value = 3.0
}

**Comment by lammas** [comment]
Should be fixed in 1.0.7.
