### ISSUE TITLE
Newlines should not be stripped from #define statements

### ISSUE THREAD

**Issue by mikecao** [lammas/glsl-man#5]
If you tell the parser to strip newlines but have code like this:

```
#define SOMEVALUE 1
uniform vec3 color;
```

You'll end up with:

```
#define SOMVALUE1uniform vec3 color;
```

Great work on this project by the way :+1:

**Comment by lammas** [comment]
Thanks, this means a lot.
This hasn't really been used as a minifier yet, I'll see what I can do about this.

**Comment by lammas** [comment]
Hopefully this works, because I could not reproduce the part with the missing spaces.

**Comment by mikecao** [comment]
Works perfectly, thanks!
